### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by guimvmatos** [DiegoRossiMafioletti/smartnic-p4#1]
Hi Diego, 

Your link to [netronome Documentation](https://github.com/nerds-ufes/agilio-p4/blob/master/agilio-sdk/doc/release-notes-nfp-sdk-rn-6.0.4.1-3276.pdf) is broken. Do you have another link?

**Comment by guimvmatos** [comment]
I see that the repo is also not available. Perhaps this repo is private.
```
$ git clone git@github.com:nerds-ufes/agilio-p4.git
```
Can you help me with this?

**Comment by DiegoRossiMafioletti** [comment]
Hi Guilherme,

I suppose that you are a Verdi’s student, welcome to the “SmartNIC world”. Sorry, but I have made a copy of another repository and I forgot to change some links. I just fixed it and now you can access normally.

About the Agilio-p4 repository, this is a private repo with projects that will be published, so for now, we need to keep in secret!

Best wishes.

--
Diego Rossi Mafioletti.

**Comment by guimvmatos** [comment]
Yes, I am Verdi's student. Thanks for sharing your experience.
